"""Train the estimator recommender and freeze it into the package.

Generates synthetic problems spanning generative ensembles and a range of (p, n) — hence regimes —
labels each by the estimator with the best out-of-sample GMV score, fits a small decision tree on
the observable covariance features, and *exports the tree as numpy-only arrays* to
``precise/_recommender_model.py``. Inference (``precise.suggest``) then needs no sklearn — it walks
the frozen tree. This is the humpday-style "train offline, ship a frozen model" pattern.

    pip install precise[research]   # needs scikit-learn
    python research/train_recommender.py
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
from sklearn.tree import DecisionTreeClassifier

from precise import all_estimators, covariance_features
from precise.assessment import GMVVariance
from research.oos import ENSEMBLES, _sample

FEATURES = [
    "p_over_n", "effective_rank", "sphericity", "condition_number",
    "mean_abs_offdiag_corr", "avg_excess_kurtosis", "p",
]
_OUT = Path(__file__).resolve().parents[1] / "precise" / "_recommender_model.py"


def _features(X):
    f = covariance_features(X)
    return [float(f[k]) for k in FEATURES]


def generate(n_problems=800, seed=0):
    rng = np.random.default_rng(seed)
    assessor = GMVVariance()
    ests = all_estimators()
    names = [E.__name__ for E in ests]
    ens_keys = list(ENSEMBLES)
    Xf, y = [], []
    for _ in range(n_problems):
        gen_fn, heavy = ENSEMBLES[ens_keys[rng.integers(len(ens_keys))]]
        p = int(rng.choice([15, 25, 40, 60]))
        n = max(int(p * rng.choice([0.5, 0.8, 1.5, 3.0])), 10)
        true = gen_fn(p, rng)
        train, test = _sample(true, n, rng, heavy), _sample(true, 400, rng, heavy)
        scores = [assessor.score(E().fit(train).covariance_, X_test=test) for E in ests]
        Xf.append(_features(train))
        y.append(names[int(np.argmax(scores))])
    return np.array(Xf, dtype=float), np.array(y), names


def export(clf, mean, std):
    t = clf.tree_
    docstring = (
        '"""Frozen recommender model (auto-generated by research/train_recommender.py).\n'
        "Numpy-only decision tree walked by precise.suggest; do not edit by hand.\n"
        '"""'
    )
    lines = [
        docstring,
        "",
        f"FEATURES = {FEATURES!r}",
        f"MEAN = {[round(float(v), 6) for v in mean]!r}",
        f"STD = {[round(float(v), 6) for v in std]!r}",
        f"CLASSES = {list(clf.classes_)!r}",
        f"FEATURE = {t.feature.tolist()!r}",
        f"THRESHOLD = {[round(float(v), 6) for v in t.threshold]!r}",
        f"LEFT = {t.children_left.tolist()!r}",
        f"RIGHT = {t.children_right.tolist()!r}",
        f"VALUE = {[[int(c) for c in node[0]] for node in t.value]!r}",
        "",
    ]
    _OUT.write_text("\n".join(lines))


def main():
    X, y, names = generate()
    mean, std = X.mean(0), X.std(0) + 1e-9
    Xs = (X - mean) / std
    clf = DecisionTreeClassifier(max_depth=5, min_samples_leaf=10, random_state=0).fit(Xs, y)
    print(f"trained on {len(y)} problems; train accuracy = {clf.score(Xs, y):.3f}")
    print("label distribution:", {n: int((y == n).sum()) for n in sorted(set(y))})
    export(clf, mean, std)
    print(f"wrote {_OUT.relative_to(_OUT.parents[1])}")


if __name__ == "__main__":
    main()
