"""Train the estimator recommender and freeze it into the package.

Generates synthetic problems spanning generative ensembles and a range of (p, n) — hence regimes —
labels each by the estimator with the best out-of-sample GMV score, fits a small decision tree on
the observable covariance features, and *exports the tree as numpy-only arrays* to
``precise/_recommender_model.py``. Inference (``precise.suggest``) then needs no sklearn — it walks
the frozen tree. This is the humpday-style "train offline, ship a frozen model" pattern.

    pip install precise[research]   # needs scikit-learn
    python research/train_recommender.py

**Is a recommender worth having?** Measured over eleven generative ensembles and seven (p, n)
regimes, by mean rank of the chosen estimator against the per-trial oracle (lower is better):

    recommender 4.37 | NonlinearShrinkage 4.21 | WindowedNonlinearShrinkage 4.39
    OAS 8.06 | Diagonal 10.70

On average, then, picking one good fixed estimator matches the recommender, and the averages hide
the reason to keep it. NonlinearShrinkage is a strong default that collapses where p approaches n:
at p=40, n=40 it ranks 9.41 while the recommender ranks 4.92. The recommender earns its place by
covering that regime, not by being better everywhere, and it is beaten at p=25, n=60 and p=8, n=200.

Two designs were tried and rejected. Always returning the strong default gives up the p-near-n case,
which is the regime high-dimensional covariance estimation exists for. Gating on the tree's leaf
purity, so the default is used unless the model is confident, was worse than the default alone at
every threshold tested (best 4.36 against 4.17): when the tree is confident it is not adding enough
to pay for the times it is confidently wrong.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
from sklearn.tree import DecisionTreeClassifier

from precise import all_estimators, covariance_features
from precise.assessment import GMVVariance
from research.oos import ENSEMBLES, _sample

FEATURES = [
    "p_over_n", "effective_rank", "sphericity", "condition_number",
    "mean_abs_offdiag_corr", "avg_excess_kurtosis", "p",
]
_OUT = Path(__file__).resolve().parents[1] / "precise" / "_recommender_model.py"


def _features(X):
    f = covariance_features(X)
    return [float(f[k]) for k in FEATURES]


def generate(n_problems=1500, seed=0):
    rng = np.random.default_rng(seed)
    assessor = GMVVariance()
    ests = all_estimators()
    names = [E.__name__ for E in ests]
    ens_keys = list(ENSEMBLES)
    Xf, y = [], []
    for _ in range(n_problems):
        gen_fn, heavy = ENSEMBLES[ens_keys[rng.integers(len(ens_keys))]]
        # The grid has to span the regimes users actually bring. An earlier version stopped at
        # n/p = 3, so every data-rich low-dimensional problem was extrapolation, and the tree
        # answered those with DiagonalCovariance when the truth was NonlinearShrinkage.
        p = int(rng.choice([5, 8, 15, 25, 40, 60]))
        n = int(np.clip(p * rng.choice([0.5, 0.8, 1.5, 3.0, 8.0, 25.0]), 10, 2000))
        true = gen_fn(p, rng)
        train, test = _sample(true, n, rng, heavy), _sample(true, 400, rng, heavy)
        scores = [assessor.score(E().fit(train).covariance_, X_test=test) for E in ests]
        Xf.append(_features(train))
        y.append(names[int(np.argmax(scores))])
    return np.array(Xf, dtype=float), np.array(y), names


def export(clf, mean, std):
    t = clf.tree_
    # tree_.value holds class *proportions* (each row sums to 1), not counts. Casting those with
    # int() floors every value under 1.0 to zero, which silently empties the model: only a
    # perfectly pure leaf survives. Multiply back by the node's sample count to recover counts.
    counts = [
        [int(round(c * n)) for c in node[0]] for node, n in zip(t.value, t.n_node_samples)
    ]
    docstring = (
        '"""Frozen recommender model (auto-generated by research/train_recommender.py).\n'
        "Numpy-only decision tree walked by precise.suggest; do not edit by hand.\n"
        '"""'
    )
    lines = [
        docstring,
        "# ruff: noqa: E501  (generated data tables: tree arrays are single long lines by design)",
        "",
        f"FEATURES = {FEATURES!r}",
        f"MEAN = {[round(float(v), 6) for v in mean]!r}",
        f"STD = {[round(float(v), 6) for v in std]!r}",
        # str(), not list(): clf.classes_ holds numpy scalars, and numpy 2 reprs those as
        # np.str_('...'), which does not parse in a module that imports no numpy.
        f"CLASSES = {[str(c) for c in clf.classes_]!r}",
        f"FEATURE = {t.feature.tolist()!r}",
        f"THRESHOLD = {[round(float(v), 6) for v in t.threshold]!r}",
        f"LEFT = {t.children_left.tolist()!r}",
        f"RIGHT = {t.children_right.tolist()!r}",
        f"VALUE = {counts!r}",
        "",
    ]
    _OUT.write_text("\n".join(lines))


def main():
    X, y, names = generate()
    mean, std = X.mean(0), X.std(0) + 1e-9
    Xs = (X - mean) / std
    clf = DecisionTreeClassifier(max_depth=5, min_samples_leaf=10, random_state=0).fit(Xs, y)
    print(f"trained on {len(y)} problems; train accuracy = {clf.score(Xs, y):.3f}")
    print("label distribution:", {n: int((y == n).sum()) for n in sorted(set(y))})
    export(clf, mean, std)
    print(f"wrote {_OUT.relative_to(_OUT.parents[1])}")


if __name__ == "__main__":
    main()
